homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: -1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
      
zone 1:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:account-multiple

# Enables the frontend
frontend:
  javascript_version: es5

# Enables configuration UI
config:

map:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically   
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55632313838351813140-if00

zwave:
  usb_path: /dev/ttyACM1

ios:

mqtt:
  broker: 127.0.0.1

device_tracker:
  - platform: owntracks

influxdb:
  host: 127.0.0.1
  username: home-assistant
  password: !secret influxdb_password
  
input_number:
  thermostat_heat_target:
    name: Set Heat Target
    min: 0
    max: 30
    step: 0.5

# Includes  
media_player: !include media_player.yaml
light: !include light.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation
recorder: !include recorder.yaml


