homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: -1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: es5

# Enables configuration UI
config:

map:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically   
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55632313838351813140-if00

mqtt:
  broker: domotica.vanlent.net
  port: 1883
  username: ha
  password: !secret mqtt_password
  
zwave:
  usb_path: /dev/ttyACM1

device_tracker:
  - platform: owntracks

influxdb:
  host: 127.0.0.1
  username: home-assistant
  password: !secret influxdb_password

# Includes  
automation: !include_dir_merge_list automation
climate: !include climate.yaml
group: !include groups.yaml
history_graph: !include history_graph.yaml
ios: !include ios.yaml
light: !include light.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
script: !include_dir_merge_list scripts
sensor: !include sensors.yaml
switch: !include switch.yaml
zone: !include zone.yaml



