homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: -1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

frontend:

config:

map:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  
updater:

discovery:

conversation:

history:

logbook:

tts:
  - platform: google

homekit:
  auto_start: False
  filter:
    include_entities:
      - climate.thermostaat
      - light.huiskamer_lamp
      - light.dressoir_lamp
      - light.nachtlampen
      - light.slaapkamer_lamp
  
rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55632313838351813140-if00

mqtt:
  broker: domotica.vanlent.net
  port: 1883
  username: ha
  password: !secret mqtt_password
  
device_tracker:
  - platform: owntracks
  - platform: ping
    hosts:
      icmp_remco: 10.10.0.52  
      icmp_denise: 10.10.0.68

alarm_control_panel: !include alarm.yaml  
automation: !include_dir_merge_list automation
climate: !include climate.yaml
group: !include groups.yaml
history_graph: !include history_graph.yaml
ios: !include ios.yaml
light: !include light.yaml
media_player: !include media_player.yaml
recorder: !include recorder.yaml
script: !include_dir_merge_list scripts
sensor: !include sensors.yaml
switch: !include switch.yaml
zone: !include zone.yaml



