- alias: Notify Denise Leaving Work Di-Do
  trigger:
    platform: time
    at: '16:45:00'
  condition: 
    condition: and
    conditions:
      - condition: time
        weekday:
          - tue
          - thu
      - condition: state
        entity_id: 'device_tracker.denise_denise'
        state: 'Work'
  action:  
    - service: notify.ios_iphone_van_denise
      data_template:
        title: Reisinformatie
        message: >
          Je verwachtte reistijd is {{ states.sensor.travel_time_denise_to_home.state }} minuten.
          Zal ik de verwarming voor je aanzetten?
        data:
          push:
            badge: 5
            category: "heater"
          action_data:
            entity_id: climate.thermostaat
- alias: Notify Denise Leaving Work Wo-Vr
  trigger:
    platform: time
    at: '18:00:00'
  condition: 
    condition: and
    conditions:
      - condition: time
        weekday:
          - wed
          - fri
      - condition: state
        entity_id: 'device_tracker.denise_denise'
        state: 'Work'
  action:  
    - service: notify.ios_iphone_van_denise
      data_template:
        title: Reisinformatie
        message: >
          Je verwachtte reistijd is {{ states.sensor.travel_time_denise_to_home.state }} minuten.
          Zal ik de verwarming voor je aanzetten?
        data:
          push:
            badge: 5
            category: "heater"
          action_data: 
            entity_id: climate.thermostaat           